# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- EuronewsTest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'EuronewsTest/EuroNewsTest.sln'
